"""Sim MCP fleet registry — discovers and tracks available simulation backends."""

SIM_BACKENDS = {
    "mujoco": {
        "name": "MuJoCo (DeepMind)",
        "backend_url": "http://127.0.0.1:11046",
        "frontend_url": "http://127.0.0.1:11047",
        "health": "/health",
        "strengths": ["fast physics", "differentiable", "GPU parallel", "contact-rich"],
        "weaknesses": ["minimal sensors", "no ROS"],
    },
    "gazebo": {
        "name": "Gazebo (OSRF)",
        "backend_url": "http://127.0.0.1:10991",
        "frontend_url": "http://127.0.0.1:10990",
        "health": "/health",
        "strengths": ["sensor simulation", "ROS native", "terrains", "outdoor"],
        "weaknesses": ["slow", "heavy", "no GPU physics"],
    },
    "isaac": {
        "name": "Isaac Sim (NVIDIA)",
        "backend_url": "http://127.0.0.1:11049",
        "frontend_url": "http://127.0.0.1:11048",
        "health": "/health",
        "strengths": ["photorealistic", "GPU physics", "synthetic data", "RTX"],
        "weaknesses": ["NVIDIA GPU required", "heavy (~10 GB)", "slow startup"],
    },
    "limx": {
        "name": "LimX Robotics",
        "backend_url": "http://127.0.0.1:11044",
        "frontend_url": "http://127.0.0.1:11045",
        "health": "/health",
        "strengths": ["hardware-specific", "VLA policies", "RL deploy"],
        "weaknesses": ["robot-specific", "MuJoCo only", "Python 3.8 req"],
    },
    "unitree": {
        "name": "Unitree Robotics",
        "backend_url": "http://127.0.0.1:11052",
        "frontend_url": "http://127.0.0.1:11053",
        "health": "/health",
        "strengths": ["quadruped Go2", "humanoid H1/G1", "ROS 2 native", "10+ models"],
        "weaknesses": ["MuJoCo GUI viewer", "no Python 3.8 req"],
    },
    "resonite": {
        "name": "Resonite (XR)",
        "backend_url": "http://127.0.0.1:10979",
        "frontend_url": "http://127.0.0.1:10978",
        "health": "/health",
        "strengths": ["XR worlds", "spatial audio", "avatar interaction", "multi-user"],
        "weaknesses": ["not a physics sim", "VR hardware", "Proton/dotnet runtime"],
    },
    "unity3d": {
        "name": "Unity 3D",
        "backend_url": "http://127.0.0.1:10831",
        "frontend_url": "http://127.0.0.1:10830",
        "health": "/health",
        "strengths": ["real-time 3D", "physics engine", "cross-platform", "asset pipeline"],
        "weaknesses": ["Unity Editor license", "C# scripting", "heavy"],
    },
    "vrchat": {
        "name": "VRChat",
        "backend_url": "http://127.0.0.1:10712",
        "frontend_url": "http://127.0.0.1:10712",
        "health": "/health",
        "strengths": ["social VR", "user-generated worlds", "avatars", "multi-user"],
        "weaknesses": ["VRChat client required", "no physics API", "rate limited"],
    },
    "worldlabs": {
        "name": "World Labs (Marble)",
        "backend_url": "http://127.0.0.1:10865",
        "frontend_url": "http://127.0.0.1:10864",
        "health": "/health",
        "strengths": ["3D world generation", "image-to-world", "text-to-world", "splat rendering"],
        "weaknesses": ["cloud API", "not real-time", "credit cost"],
    },
    "blender": {
        "name": "Blender",
        "backend_url": "http://127.0.0.1:10849",
        "frontend_url": "http://127.0.0.1:10848",
        "health": "/health",
        "strengths": ["3D modelling", "furniture/assets", "sculpting", "animation"],
        "weaknesses": ["not real-time", "Python API overhead", "headless mode limited"],
    },
}
