"""
B-9 - Lost in Space
Generated by Gemini AI

Creates the iconic B-9 robot from the 1965-1968 TV series "Lost in Space".
Features the classic design with:
- Tread-powered base with caterpillar tracks
- Central leg pillar supporting the torso
- Accordion-style torso made of stacked flexible rings
- Brain dome on top with compressed appearance
- Friendly robot aesthetic from 1960s sci-fi

Author: Gemini AI
Category: robots
Tags: classic, tv, sci-fi, lost-in-space, b9, friendly-robot
Dimensions: ~180cm tall
Complexity: medium
"""

import bpy

# 1. The Tread Base
bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, 15))
base = bpy.context.active_object
base.dimensions = (80, 100, 30)
base.name = "B9_Base"

# 2. The Leg Section (Pillar)
bpy.ops.mesh.primitive_cylinder_add(radius=25, depth=60, location=(0, 0, 60))

# 3. The Accordion Torso (Stack of toruses)
for i in range(5):
    bpy.ops.mesh.primitive_torus_add(location=(0, 0, 100 + (i * 15)), major_radius=35, minor_radius=8)

# 4. The Brain Dome
bpy.ops.mesh.primitive_uv_sphere_add(radius=30, location=(0, 0, 180))
bpy.context.active_object.scale[2] = 0.8
