"""
C-3PO - Star Wars
Generated by Gemini AI

Creates a simplified C-3PO protocol droid from the Star Wars franchise.
Features the classic golden design with:
- Rectangular chest/torso with proper proportions
- Iconic oval head with protocol droid appearance
- Exposed mechanical waist section
- Simplified cylindrical limbs
- Golden color scheme ready for materials

Author: Gemini AI
Category: robots
Tags: star-wars, protocol-droid, c3po, droid, sci-fi, iconic
Dimensions: ~190cm tall
Complexity: medium
"""

import bpy

# 1. Torso (The 'Golden' Chest)
bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, 140))
chest = bpy.context.active_object
chest.dimensions = (40, 20, 45)
chest.name = "3PO_Chest"

# 2. Head (The Iconic Oval)
bpy.ops.mesh.primitive_uv_sphere_add(radius=12, location=(0, 0, 175))
head = bpy.context.active_object
head.scale[2] = 1.2  # Make it slightly oval

# 3. The 'Mechanical' Waist (Exposed wiring area)
bpy.ops.mesh.primitive_cylinder_add(radius=12, depth=15, location=(0, 0, 115))

# 4. Limbs (Simplified Cylinders)
for side in [-18, 18]:
    # Arms
    bpy.ops.mesh.primitive_cylinder_add(radius=4, depth=60, location=(side * 1.5, 0, 145))
    # Legs
    bpy.ops.mesh.primitive_cylinder_add(radius=6, depth=90, location=(side * 0.6, 0, 55))
