"""
Gort - The Day the Earth Stood Still
Generated by Gemini AI

Creates the iconic Gort robot from the 1951 film "The Day the Earth Stood Still".
Features the imposing design with:
- Tall, monolithic humanoid body (240cm height)
- Distinctive visor slot for laser projection
- Seamless metal appearance with subdivision surface
- Intimidating, otherworldly presence
- Proper scale for a being capable of destroying cities

Author: Gemini AI
Category: robots
Tags: classic, film, sci-fi, day-earth-stood-still, gort, alien-robot
Dimensions: ~240cm tall
Complexity: medium
"""

import bpy

# Clear scene
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()

# 1. Body (Tall, monolithic humanoid)
bpy.ops.mesh.primitive_cylinder_add(radius=25, depth=240, location=(0, 0, 120))
gort = bpy.context.active_object
gort.name = "Gort_Body"

# 2. Visor (The 'Laser' slot)
bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 18, 225))
visor = bpy.context.active_object
visor.dimensions = (40, 10, 5)
visor.name = "Gort_Visor_Slot"

# Apply a Boolean to cut the visor into the head
mod = gort.modifiers.new(name="VisorCut", type="BOOLEAN")
mod.object = visor
mod.operation = "DIFFERENCE"

# 3. Smooth it out (To look like seamless metal)
subdiv = gort.modifiers.new(name="SmoothMetal", type="SUBSURF")
subdiv.levels = 2
