"""
Robby the Robot - Forbidden Planet
Generated by Gemini AI

Creates the iconic Robby the Robot from the 1956 film "Forbidden Planet".
Features the classic design with:
- Interlocking globe legs (3 per side)
- Barrel-shaped torso
- Domed head with vacuum-formed plexiglass appearance
- Rotating scanner rings (ears)
- Proper scale and positioning for film-accurate proportions

Author: Gemini AI
Category: robots
Tags: classic, film, sci-fi, forbidden-planet, robby, humanoid
Dimensions: ~120cm tall (approximate)
Complexity: medium
"""

import bpy

# Setup Units
bpy.context.scene.unit_settings.system = "METRIC"
bpy.context.scene.unit_settings.scale_length = 0.001

# Clear scene
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()

# 1. Legs (The iconic 'interlocking globes')
for i in range(3):
    for side in [-40, 40]:
        bpy.ops.mesh.primitive_uv_sphere_add(radius=25, location=(side, 0, 20 + (i * 40)))

# 2. Barrel Torso
bpy.ops.mesh.primitive_cylinder_add(radius=60, depth=100, location=(0, 0, 150))
torso = bpy.context.active_object
torso.name = "Robby_Torso"

# 3. The Dome (Vacuum-formed Plexiglass vibe)
bpy.ops.mesh.primitive_uv_sphere_add(radius=45, location=(0, 0, 220))
dome = bpy.context.active_object
dome.scale[2] = 1.3  # Make it taller

# 4. Scanner Ears (The rotating rings)
for side in [-55, 55]:
    bpy.ops.mesh.primitive_torus_add(align="WORLD", location=(side, 0, 230), major_radius=10, minor_radius=2)
