"""
Robodog - Black Mirror Metalhead Episode
Generated by Gemini AI

Creates the terrifying quadrupedal killer robot from the Black Mirror episode "Metalhead".
Features the menacing design with:
- Sleek gun-metal chassis with sharp angular design
- Four functional legs with piston-like lower sections
- Modified front leg serving as a weapon arm
- Low-profile, predatory silhouette
- Proper scale for a dog-sized robotic predator

Author: Gemini AI
Category: robots
Tags: quadruped, predator, weapon, black-mirror, metalhead, killer-robot
Dimensions: ~80x40x25cm (chassis)
Complexity: medium
"""

import bpy

# Clear scene
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()

# 1. Main Chassis (Gun-metal finish vibe)
bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, 50))
chassis = bpy.context.active_object
chassis.dimensions = (40, 80, 25)
chassis.name = "Dog_Chassis"

# 2. Quadruped Legs (Functional & Sharp)
for x in [-22, 22]:
    for y in [-35, 35]:
        # Upper Leg (Thigh)
        bpy.ops.mesh.primitive_cylinder_add(radius=4, depth=40, location=(x, y, 30))
        thigh = bpy.context.active_object
        thigh.rotation_euler[0] = 0.5  # Slanted forward/back

        # Lower Leg (Piston)
        bpy.ops.mesh.primitive_cylinder_add(radius=2, depth=40, location=(x, y * 1.2, 10))

# 3. The Weapon Arm (Front Leg Modification)
bpy.ops.mesh.primitive_cylinder_add(radius=3, depth=15, location=(0, 45, 45))
gun = bpy.context.active_object
gun.rotation_euler[0] = 1.57  # Level with ground
