"""Minimal procedural mesh generators for ResoniteLink's spawn_mesh (importMeshJSON schema).

Verified against resonite_mcp.resonite_link.ResoniteLinkClient.spawn_mesh and the same JSON
shape used by scripts/spawn_nekomimi_in_home.py in resonite-mcp (a real, live-tested spawn):
vertices = [{"position": {"x","y","z"}}, ...]
submeshes = [{"$type": "triangles", "triangles": [{"vertex0Index","vertex1Index","vertex2Index"}, ...]}]
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger("robotics_mcp.mesh_primitives")

# norirobotics-mcp is the canonical Nori A3 integration point (sibling repo, same pattern
# already used for the unity3d-mcp/resonite-mcp sys.path additions in server.py). The mesh
# JSON here is generated by norirobotics-mcp/scripts/export_posed_mesh.py from the real,
# vendored nori_description meshes, correctly posed via MuJoCo's own forward kinematics.
_NORI_A3_MESH_JSON = (
    Path(__file__).resolve().parent.parent.parent.parent.parent
    / "norirobotics-mcp"
    / "models"
    / "nori_description"
    / "nori_a3_posed.mesh.json"
)


def box_mesh(size: float = 0.3) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """An axis-aligned unit box (side length `size`), 8 vertices / 12 triangles.

    No real 3D model exists for most vbot robot_types - this is the labeled placeholder
    shape spawned in Resonite until a real model/mesh is sourced.
    """
    h = size / 2.0
    corners = [
        (-h, -h, -h), (h, -h, -h), (h, h, -h), (-h, h, -h),
        (-h, -h, h), (h, -h, h), (h, h, h), (-h, h, h),
    ]
    vertices = [{"position": {"x": x, "y": y, "z": z}} for x, y, z in corners]

    # 6 faces, 2 triangles each, consistent outward winding.
    faces = [
        (0, 1, 2, 3),  # back
        (5, 4, 7, 6),  # front
        (4, 0, 3, 7),  # left
        (1, 5, 6, 2),  # right
        (3, 2, 6, 7),  # top
        (4, 5, 1, 0),  # bottom
    ]
    triangles = []
    for a, b, c, d in faces:
        triangles.append({"vertex0Index": a, "vertex1Index": b, "vertex2Index": c})
        triangles.append({"vertex0Index": a, "vertex1Index": c, "vertex2Index": d})

    submeshes = [{"$type": "triangles", "triangles": triangles}]
    return vertices, submeshes


def load_nori_a3_mesh() -> tuple[list[dict[str, Any]], list[dict[str, Any]]] | None:
    """Load the real, pre-baked Nori A3 mesh (vertices, submeshes) if it's been generated.

    Returns None (not an error) if norirobotics-mcp/models/.../nori_a3_posed.mesh.json doesn't
    exist yet - callers should fall back to box_mesh() rather than fail the spawn outright.
    Run norirobotics-mcp/scripts/export_posed_mesh.py to (re)generate it.
    """
    if not _NORI_A3_MESH_JSON.is_file():
        logger.warning("Nori A3 posed mesh not found at %s - falling back to placeholder box", _NORI_A3_MESH_JSON)
        return None
    try:
        data = json.loads(_NORI_A3_MESH_JSON.read_text(encoding="utf-8"))
        return data["vertices"], data["submeshes"]
    except Exception:
        logger.exception("Failed to load Nori A3 posed mesh from %s", _NORI_A3_MESH_JSON)
        return None
