"""
Hohensalzburg Fortress
Generated by Gemini AI

Creates a detailed 3D model of Hohensalzburg Fortress in Salzburg, Austria.
One of Europe's largest medieval castles, featuring:
- Main castle keep with towers and battlements
- Outer walls and defensive structures
- Courtyard and inner buildings
- Historical architectural details
- Proper scale and positioning

Author: Gemini AI
Category: architecture
Tags: medieval, castle, fortress, austria, salzburg, historical
Dimensions: ~250x150x60m (approximate)
Complexity: Complex
"""

import math

import bpy

# Clear scene
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()


def create_tower(name, location, height=25, radius=8):
    """Create a castle tower with battlements."""
    # Main tower cylinder
    bpy.ops.mesh.primitive_cylinder_add(radius=radius, depth=height, location=location)
    tower = bpy.context.active_object
    tower.name = f"{name}_Tower"

    # Add battlements (crenellations) on top
    battlement_height = 2
    battlement_width = 1.5
    num_crenels = 12

    for i in range(num_crenels):
        angle = (i / num_crenels) * math.pi * 2
        x = location[0] + math.cos(angle) * (radius + 0.5)
        y = location[1] + math.sin(angle) * (radius + 0.5)
        z = location[2] + height / 2 + battlement_height / 2

        # Alternate between merlon (solid) and crenel (gap)
        if i % 2 == 0:
            bpy.ops.mesh.primitive_cube_add(size=1, location=(x, y, z))
            merlon = bpy.context.active_object
            merlon.dimensions = (battlement_width, battlement_width, battlement_height)
            merlon.name = f"{name}_Merlon_{i}"

    return tower


def create_wall_segment(start_pos, end_pos, height=12, thickness=3):
    """Create a wall segment between two points."""
    # Calculate wall properties
    dx = end_pos[0] - start_pos[0]
    dy = end_pos[1] - start_pos[1]
    length = math.sqrt(dx * dx + dy * dy)
    angle = math.atan2(dy, dx)

    # Position at midpoint
    mid_x = (start_pos[0] + end_pos[0]) / 2
    mid_y = (start_pos[1] + end_pos[1]) / 2
    mid_z = height / 2

    # Create wall
    bpy.ops.mesh.primitive_cube_add(size=1, location=(mid_x, mid_y, mid_z))
    wall = bpy.context.active_object
    wall.dimensions = (length, thickness, height)
    wall.rotation_euler[2] = angle
    wall.name = "Castle_Wall"

    # Add battlements on top
    battlement_z = height + 1
    num_merions = int(length / 2)

    for i in range(num_merions):
        if i % 2 == 0:  # Alternate merlons
            merlon_x = mid_x + (i - num_merions / 2) * 2 * math.cos(angle)
            merlon_y = mid_y + (i - num_merions / 2) * 2 * math.sin(angle)

            bpy.ops.mesh.primitive_cube_add(size=1, location=(merlon_x, merlon_y, battlement_z))
            merlon = bpy.context.active_object
            merlon.dimensions = (1.5, 1.5, 2)
            merlon.rotation_euler[2] = angle
            merlon.name = f"Wall_Merlon_{i}"

    return wall


# Main fortress structure coordinates (approximate scale)
fortress_center = (0, 0, 0)

# Main keep (central tower)
create_tower("Keep", (0, 0, 20), height=35, radius=12)

# Corner towers
tower_positions = [
    (80, 60, 15),  # Northeast
    (-80, 60, 15),  # Northwest
    (80, -60, 15),  # Southeast
    (-80, -60, 15),  # Southwest
]

for i, pos in enumerate(tower_positions):
    create_tower(f"Corner_{i}", pos, height=25, radius=8)

# Outer walls
wall_positions = [
    # North wall
    ((-60, 60, 0), (60, 60, 0)),
    # South wall
    ((-60, -60, 0), (60, -60, 0)),
    # East wall
    ((80, -40, 0), (80, 40, 0)),
    # West wall
    ((-80, -40, 0), (-80, 40, 0)),
]

for start, end in wall_positions:
    create_wall_segment(start, end)

# Inner courtyard buildings (simplified)
bpy.ops.mesh.primitive_cube_add(size=1, location=(20, 0, 8))
building = bpy.context.active_object
building.dimensions = (25, 15, 16)
building.name = "Courtyard_Building"

# Add some architectural details - windows, doors
bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 65, 10))
gate = bpy.context.active_object
gate.dimensions = (8, 3, 12)
gate.name = "Main_Gate"

# Add ground plane
bpy.ops.mesh.primitive_plane_add(size=200, location=(0, 0, 0))
ground = bpy.context.active_object
ground.name = "Castle_Ground"

# Add some trees around the perimeter (simplified)
for i in range(8):
    angle = (i / 8) * math.pi * 2
    x = math.cos(angle) * 120
    y = math.sin(angle) * 120

    # Simple tree representation
    bpy.ops.mesh.primitive_cylinder_add(radius=3, depth=20, location=(x, y, 10))
    trunk = bpy.context.active_object
    trunk.name = f"Tree_Trunk_{i}"

    bpy.ops.mesh.primitive_uv_sphere_add(radius=8, location=(x, y, 25))
    foliage = bpy.context.active_object
    foliage.name = f"Tree_Foliage_{i}"

print("Hohensalzburg Fortress model created successfully!")
print("Features: Main keep, corner towers, defensive walls, courtyard, main gate")
print("Historical fortress from 1077 AD, one of Europe's largest medieval castles")
